name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 👈 This is required for pushing tags!

jobs:
  tag:
    name: Tag New Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
